name: "Junit Report to Annotations"
description: "Add check runs to your CI with annotations listing the test failures"
branding:
  icon: "box"
  color: "green"
inputs:
  access-token:
    description: "Github token (generally secrets.GITHUB_TOKEN)"
    required: true
  path:
    description: "Glob to JUnit XML files"
    required: true
    default: "**/TEST-*.xml"
  numFailures:
    description: "Max number of failed tests to include (-1 for no limit)"
    required: true
    default: "-1"
  name:
    description: "Name of the Check in the GitHub Actions UI (if you use several times this action)"
    required: true
    default: "Junit Report"
runs:
  using: "node12"
  main: "index.js"
