name: Tests

on:
  pull_request:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test

  # Run this action on itself. Even if there is no JUnit reports, the action should run silently without errors.

  ubuntu-action-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ashley-taylor/junit-report-annotations-action@1.3
        with:
          name: "unbuntu unit tests"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/TEST-*.xml"

  macos-action-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ashley-taylor/junit-report-annotations-action@1.3
        with:
          name: "macos unit tests"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/TEST-*.xml"
