name: Tests

on:
  pull_request:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test

  # Run this action on itself. Even if there is no JUnit reports, the action should run silently without errors.

  ubuntu-action-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ./
        with:
          name: "ubuntu failed tests"
          access-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./
        with:
          name: "ubuntu valid tests"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/TEST-*-Success.xml"

  macos-action-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ./
        with:
          name: "macos failed tests"
          access-token: ${{ secrets.GITHUB_TOKEN }}
